services:
  postgres:
    image: postgres:15        # Back to 15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fincore
      TZ: UTC                 # Add timezone
      PGTZ: UTC
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: